
# Version - Compose file version that tells compose how to build and run containers
version: '3.3'

# Services: A list of all the containers that we want on my docker network
services:

    # MySQL service
    bedoff_mysqldb:
        container_name: "bedoff_mysqldb"
        build: ./docker/mysql
        hostname: bedoff_mysqldb
        tty: true
        ports:
            - '3307:3306'
        # Environment used to create the relevant DB and user
        environment:
            MYSQL_DATABASE: bedoff
            MYSQL_USER: bedoff
            MYSQL_PASSWORD: bedoff
            MYSQL_ROOT_PASSWORD: bedoff
        # Specifying a restart policy for the containerized service
        restart: always
        volumes:
            - ./log/mysql:/var/log/mysql
        networks:
            - bedoff-network

    # bedoff-backend service(web application service)
    bedoff-backend-api:
        links:
            - bedoff_mysqldb
        container_name: "bedoff-backend-api"
        hostname: bedoff-backend-api
        build:
            context: .
        command: 'python3 manage.py runserver 0.0.0.0:8000'
        volumes:
            - '.:/bedoff'
        ports:
            - '8000:8000'
        # This is for the debugger on the environment
        stdin_open: true
        tty: true
        # Specifying a restart policy for the containerized service
        restart: always
        networks:
            - bedoff-network
        depends_on:
            - bedoff_mysqldb

networks:
  bedoff-network:
    driver: bridge
