# Generated by Django 3.2.12 on 2022-04-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=5)),
                ('active', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(max_length=4)),
                ('ordered_on', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(max_length=4)),
                ('checkIn', models.DateTimeField(auto_now=True)),
                ('checkOut', models.DateTimeField(auto_now=True)),
                ('NumberOfRooms', models.IntegerField()),
                ('SuggestedHotelList', models.CharField(max_length=100)),
                ('TypeOfBookings', models.CharField(max_length=100)),
                ('BookingType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=2)),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bms.bookingorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('lastUpdatedOn', models.DateTimeField(auto_now=True)),
                ('active', models.CharField(max_length=4)),
                ('BookingGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.bookinggroup')),
                ('Visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.visitor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
