# Generated by Django 3.2.12 on 2022-04-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_auto_20220402_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor',
            new_name='Guest',
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedOn', models.DateTimeField(auto_now=True)),
                ('BookingGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.bookinggroup')),
            ],
        ),
    ]
