# Generated by Django 3.2.12 on 2022-04-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelstaff',
            name='role',
            field=models.CharField(choices=[('RM', 'Regional Manager'), ('OW', 'Owner'), ('MN', 'Manager'), ('RC', 'Receptionist')], max_length=2),
        ),
    ]
