# Generated by Django 3.2.13 on 2022-04-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1024)),
                ("address1", models.CharField(max_length=1024)),
                ("address2", models.CharField(max_length=1024)),
                ("zip_code", models.CharField(max_length=12)),
                ("city", models.CharField(max_length=1024)),
                ("country", models.CharField(max_length=3)),
                ("MapLink", models.CharField(max_length=400)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="", max_length=100)),
                ("address", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="hotels.address")),
                (
                    "manager",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="accounts.hotelstaff"
                    ),
                ),
            ],
        ),
    ]
