# Generated by Django 3.2.13 on 2022-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotel",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
