# Generated by Django 3.2.13 on 2022-04-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="account",
        ),
        migrations.AlterField(
            model_name="hotel",
            name="general_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="general_manager",
                to="hotels.hotelstaff",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="manager",
                to="hotels.hotelstaff",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="owner",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="owner", to="hotels.hotelstaff"
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="receptionist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="receptionist",
                to="hotels.hotelstaff",
            ),
        ),
    ]
