# Generated by Django 3.2.13 on 2022-04-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_fields_to_hotels'),
        ('hotels', '0002_add_base_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_plan', models.IntegerField(choices=[(1, 'Plan 1'), (2, 'Plan 2')])),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.bankaccount'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='general_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_manager', to='accounts.hotelstaff'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='accounts.hotelstaff'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionist', to='accounts.hotelstaff'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to='accounts.hotelstaff'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
