# Generated by Django 3.2.13 on 2022-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteladdress",
            name="state",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
