# Generated by Django 3.2.13 on 2022-04-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_added_state_to_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteladdress",
            name="country",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
