# Generated by Django 3.2.13 on 2022-04-30 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_relaxed_country_char_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="general_manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="general_manager_hotels",
                to="hotels.hotelstaff",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="manager_hotels",
                to="hotels.hotelstaff",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="owner_hotels",
                to="hotels.hotelstaff",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="receptionist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="receptionist_hotels",
                to="hotels.hotelstaff",
            ),
        ),
        migrations.AlterField(
            model_name="hoteladdress",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hotel_address",
                to="hotels.hotel",
            ),
        ),
    ]
