# Generated by Django 3.2.13 on 2022-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_hotel_address_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hoteladdress",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hotelstaff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
