# Generated by Django 3.2.13 on 2022-05-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotel_and_booking_model_updates'),
        ('hotels', '0007_hotel_and_booking_model_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_account', to='accounts.userbankaccount'),
        ),
    ]
