# Generated by Django 3.2.13 on 2022-05-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0010_updated_date_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="address_link",
        ),
    ]
