# Generated by Django 3.2.13 on 2022-05-15 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_remove_hotel_address_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_account', to='hotels.hotelbankaccount'),
        ),
    ]
