# Generated by Django 3.2.13 on 2022-05-23 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0012_hotel_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="account",
        ),
        migrations.AddField(
            model_name="hotelbankaccount",
            name="hotel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hotel_bank_account",
                to="hotels.hotel",
            ),
        ),
    ]
