# Generated by Django 3.2.13 on 2022-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_fk_hotel_bank_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tariff_double_occupancy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tariff_single_occupancy',
            field=models.IntegerField(null=True),
        ),
    ]
