# Generated by Django 3.2.13 on 2022-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_add_tarrif_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
