# Generated by Django 3.2.13 on 2022-05-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_add_email_to_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='additional_email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
