# Generated by Django 3.2.13 on 2022-05-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0016_add_additionalemai_to_hotel_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteladdress",
            name="hotel",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hotel_address",
                to="hotels.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="hotelbankaccount",
            name="hotel",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="hotel_bank_account",
                to="hotels.hotel",
            ),
        ),
    ]
