# Generated by Django 3.2.13 on 2022-04-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=5)),
                ("IFSC", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=5)),
                ("mail", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=5)),
                ("active", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HotelStaff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=5)),
                ("mail", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=5)),
                ("active", models.BooleanField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("RM", "Regional Manager"),
                            ("OW", "Owner"),
                            ("MN", "Manager"),
                            ("RC", "Receptionist"),
                        ],
                        max_length=2,
                    ),
                ),
                ("status", models.IntegerField()),
                ("hotel", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="hotels.hotel")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HotelAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.bankaccount")),
                ("hotel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel")),
            ],
        ),
    ]
