# Generated by Django 3.2.13 on 2022-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='IFSC',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hotelstaff',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotelstaff',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotelstaff',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hotelstaff',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='HotelAccount',
        ),
    ]
