# Generated by Django 3.2.13 on 2022-05-05 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0010_updated_date_booking"),
        ("accounts", "0002_hotel_and_booking_model_updates"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserBankAccount",
        ),
    ]
