# Generated by Django 3.2.13 on 2022-04-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checkIn", models.DateTimeField(auto_now=True)),
                ("checkOut", models.DateTimeField(auto_now=True)),
                ("PreferredHotels", models.CharField(default="", max_length=50)),
                ("NumberOfRooms", models.IntegerField()),
                ("SuggestedHotelList", models.CharField(max_length=100)),
                ("BookingType", models.IntegerField(choices=[(1, "New Booking"), (2, "Extension")])),
                ("TypeOfBookings", models.IntegerField(choices=[(1, "HNS"), (2, "Relocation")])),
                (
                    "Status",
                    models.IntegerField(
                        choices=[(1, "In Progress"), (2, "Completed"), (3, "Closed"), (4, "Cancelled")], default=1
                    ),
                ),
                ("Hotel", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="hotels.hotel")),
            ],
        ),
    ]
