# Generated by Django 3.2.13 on 2022-04-29 11:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("employee_id", models.CharField(default="", max_length=100)),
                ("first_name", models.CharField(default="", max_length=100)),
                ("last_name", models.CharField(default="", max_length=100)),
                ("booking_id", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="guest_createdby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="guest_modifiedby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("check_in", models.DateTimeField(auto_now=True, null=True)),
                ("check_out", models.DateTimeField(auto_now=True, null=True)),
                ("booking_type", models.IntegerField(choices=[(1, "New Booking"), (2, "Extension")], default=1)),
                ("stay_type", models.IntegerField(choices=[(1, "HNS"), (2, "Relocation")])),
                (
                    "booking_status",
                    models.IntegerField(
                        choices=[(1, "In Progress"), (2, "Completed"), (3, "Closed"), (4, "Cancelled")], default=1
                    ),
                ),
                ("single_occupancy_room_count", models.IntegerField(null=True)),
                ("double_occupancy_room_type", models.IntegerField(null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="booking_createdby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("guests", models.ManyToManyField(to="bookings.Guest")),
                (
                    "hotel",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hotels.hotel"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="booking_modifiedby",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
