# Generated by Django 3.2.13 on 2022-04-14 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("employee_TNLID", models.CharField(default="", max_length=100)),
                ("name", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_in", models.DateTimeField(auto_now=True, null=True)),
                ("check_out", models.DateTimeField(auto_now=True, null=True)),
                ("preferred_hotels", models.CharField(default="", max_length=50)),
                ("booking_type", models.IntegerField(choices=[(1, "New Booking"), (2, "Extension")])),
                ("type_of_booking", models.IntegerField(choices=[(1, "HNS"), (2, "Relocation")])),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "In Progress"), (2, "Completed"), (3, "Closed"), (4, "Cancelled")], default=1
                    ),
                ),
                ("room_sount_single_occupancy", models.IntegerField()),
                ("room_count_double_occupancy", models.IntegerField()),
                ("guest_count", models.IntegerField()),
                ("guest", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="bookings.guest")),
            ],
        ),
    ]
