# Generated by Django 3.2.13 on 2022-04-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="bookings.guest"),
        ),
    ]
