# Generated by Django 3.2.13 on 2022-04-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="Hotel",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hotels.hotel"),
        ),
    ]
