# Generated by Django 3.2.13 on 2022-04-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_guest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="guest",
            new_name="guests",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="room_sount_single_occupancy",
            new_name="room_count_single_occupancy",
        ),
    ]
