# Generated by Django 3.2.13 on 2022-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_removed_booking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
