# Generated by Django 3.2.13 on 2022-04-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="Hotel",
        ),
    ]
