# Generated by Django 3.2.13 on 2022-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_hotel_and_booking_model_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guests",
            field=models.ManyToManyField(null=True, to="bookings.Guest"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="stay_type",
            field=models.IntegerField(choices=[(1, "HNS"), (2, "Relocation")], null=True),
        ),
    ]
