# Generated by Django 3.2.13 on 2022-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_removed_non_null_constraint_guests_stay_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(null=True),
        ),
    ]
