# Generated by Django 3.2.13 on 2022-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_change_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="booking_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
