# Generated by Django 3.2.13 on 2022-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_updated_booking_occupany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="double_occupancy_room_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="booking",
            name="single_occupancy_room_count",
            field=models.IntegerField(default=0),
        ),
    ]
