# Generated by Django 3.2.13 on 2022-04-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0004_modify_choices"),
        ("bookings", "0007_add_base_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booked_hotel",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hotels.hotel"),
        ),
    ]
