# Generated by Django 3.2.13 on 2022-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_updated_booking_occupany"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="advance_pay",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_pay",
            field=models.IntegerField(default=0),
        ),
    ]
