# Generated by Django 3.2.13 on 2022-05-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_add_pricefield_to_bookings_and_change_hotelrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="audit_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="audit_comments",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="bills_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_in_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_comments",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
