# Generated by Django 3.2.13 on 2022-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_models_booking_status_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="advance_pay_utr",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_pay_utr",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
